Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vm.hostname = "gitlab"

  config.vm.network "private_network", ip: "192.168.250.11"

  config.vm.synced_folder "C:\\MySpace", "/myspace"

  #config.vm.provision "shell", path: "gitlab.sh"
  config.vm.provision "shell", inline: <<-SHELL
    sudo yum update -y
    sudo yum install -y git wget
    sudo yum install -y java-1.8.0-openjdk-devel
    sudo yum install -y curl policycoreutils-python openssh-server
    sudo systemctl enable sshd
    sudo systemctl start sshd
    sudo firewall-cmd --permanent --add-service=http
    sudo systemctl reload firewalld
    sudo yum install -y postfix
    sudo systemctl enable postfix
    sudo systemctl start postfix
    curl https://packages.gitlab.com/install/repositories/gitlab/gitlab-ce/script.rpm.sh | sudo bash
    sudo EXTERNAL_URL="https://gitlab.cpw.com" yum install -y gitlab-ce
  SHELL

end
