Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vm.hostname = "gitlab"

  config.vm.network "private_network", ip: "192.168.250.11"

  config.vm.synced_folder "C:\\MySpace", "/myspace"

  #config.vm.provision "shell", path: "gitlab.sh"
  config.vm.provision "shell", inline: <<-SHELL
    sudo apt-get -y update
    sudo apt-get -y install git wget
  SHELL

end
