Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vm.hostname = "gitlab"

  config.vm.network "private_network", ip: "192.168.250.11"

  config.vm.synced_folder "C:\\MySpace", "/myspace"

  config.vm.provision "shell", path: "gitlab.sh"

end
